name: Test and publish Python package with uv

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    name: Testing and static checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.2"
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Run tests
      run: uv run pytest tests

    - name: Check type hints with BasedPyright
      run: |
        uv run basedpyright src/toml_decouple/

    - name: Run linting and format with Ruff
      run: |
        uv run ruff check .
        uv run ruff format . --check

  pypi-publish:
    name: Upload release to PyPI
    needs: test
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/toml-decouple

    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.2"
        python-version: "pyproject.toml"
        enable-cache: true

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Build the project
      run: uv build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
